"""octofit_tracker URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
import os
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.decorators import api_view
from rest_framework.response import Response

# import existing views for viewsets
from . import views

router = DefaultRouter()

# customize the API root view generated by the router so that it
# always constructs URLs using the codespace hostname.  By default
# DefaultRouter uses `request.build_absolute_uri` which picks up the
# incoming Host header and scheme; when dialling the codespace URL
# with curl the certificate can produce warnings.  This override
# ignores the request host and builds the full URL from the
# $CODESPACE_NAME environment variable instead.


router.register(r'users', views.UserViewSet, basename='user')
router.register(r'teams', views.TeamViewSet, basename='team')
router.register(r'activities', views.ActivityViewSet, basename='activity')
router.register(r'workouts', views.WorkoutViewSet, basename='workout')
router.register(r'leaderboard', views.LeaderboardViewSet, basename='leaderboard')


@api_view(['GET'])
def api_root_env(request, format=None):
    """Produce a static API root using the codespace hostname when available.
    This avoids relying on `request` data (which can produce HTTPS cert warnings)
    and guarantees the correct `https://<codespace>-8000.app.github.dev` prefix in
    endpoint URLs.
    """
    codespace = os.environ.get('CODESPACE_NAME')
    if codespace:
        base = f"https://{codespace}-8000.app.github.dev/api/"
    else:
        # fall back to request-derived absolute URI
        base = request.build_absolute_uri('/api/')
    return Response({
        'users': base + 'users/',
        'teams': base + 'teams/',
        'activities': base + 'activities/',
        'workouts': base + 'workouts/',
        'leaderboard': base + 'leaderboard/',
    })

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', api_root_env, name='api-root'),
    path('api/', include(router.urls)),
]
